### ISSUE TITLE
Problem when launching the App (Blazor Server-side)

### ISSUE THREAD

**Issue by aitlahmid** [DevExpress-Examples/XAF_how-to-use-the-integrated-mode-of-the-security-system-in-non-xaf-applications-e4908#39]
Hi

In blazor server side, when i launch the app i got the error:

![image](https://user-images.githubusercontent.com/17543477/77773762-58ec6680-704a-11ea-9e25-9d86dbf18297.png)

If I press the f5 key, the login screen is displayed.

Thank you

**Comment by AndreyKozhevnikov** [comment]
Hello,

Please refer to the [Trouble with NavigateTo within OnInitialized · Issue #13582 · dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues/13582) thread where the ASP.NET Core team discussed this issue and how to overcome it.

Thanks,
Andrey
