### ISSUE TITLE
App (Blazor Server-side) is freezing on IPad and IPhone (IOS) 

### ISSUE THREAD

**Issue by realproductions** [DevExpress-Examples/XAF_how-to-use-the-integrated-mode-of-the-security-system-in-non-xaf-applications-e4908#42]
When you view the app on a ipad or iphone (in Safari browser) the app is freezing.
Steps to reproduce:

1. Navigate to url on ipad
2. Login with Username: User or Admin
3. The datagrid is showing data but s not responding to any click

**Comment by AndreyKozhevnikov** [comment]
Hello,

I tried our demo with Safari v12 and it works as expected on my side. Please create a ticket in our Support Center and describe in detail what steps we need to perform to reproduce the issue you faced: https://supportcenter.devexpress.com/
Specify also the exact version of your browser. If you update our components in the example, specify the versions that you used.

Thanks,
Andrey
